# Generated by Django 5.0.14 on 2026-06-03 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('nome_pt', models.CharField(max_length=80, verbose_name='nome (PT)')),
                ('nome_en', models.CharField(blank=True, max_length=80, verbose_name='nome (EN)')),
                ('nota_pt', models.CharField(blank=True, max_length=200, verbose_name='nota (PT)')),
                ('nota_en', models.CharField(blank=True, max_length=200, verbose_name='nota (EN)')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardapio_atualizado_em', models.DateField(default=django.utils.timezone.now)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'configuração do site',
                'verbose_name_plural': 'configuração do site',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('desc_pt', models.CharField(blank=True, max_length=300, verbose_name='descrição (PT)')),
                ('desc_en', models.CharField(blank=True, max_length=300, verbose_name='descrição (EN)')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, help_text="Deixe vazio para 'a definir'.", max_digits=7, null=True)),
                ('destaque', models.BooleanField(default=False, verbose_name='carro-chefe')),
                ('disponivel', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cardapio.categoria')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'ordering': ['categoria__ordem', 'ordem', 'id'],
            },
        ),
    ]
