# Generated by Django 5.0.14 on 2026-06-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_sync_traducao_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=80)),
                ('texto', models.TextField()),
                ('nota', models.PositiveSmallIntegerField(default=5, verbose_name='nota (1-5)')),
                ('fonte', models.CharField(choices=[('google', 'Google'), ('tripadvisor', 'TripAdvisor'), ('outro', 'Outro')], default='google', max_length=20)),
                ('aparece', models.BooleanField(default=True, verbose_name='aparece no site')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='tripadvisor_url',
            field=models.URLField(blank=True, verbose_name='TripAdvisor (link)'),
        ),
    ]
