# Generated by Django 5.0.14 on 2026-06-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_espresso_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='ref',
            field=models.CharField(blank=True, default='', help_text='ID da avaliação na fonte (ex.: Google) — usado pelo sync p/ não duplicar.', max_length=300, verbose_name='ref. externa'),
        ),
    ]
