# Generated by Django 5.0.14 on 2026-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0008_reset_lockouts_axes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='encomendavel',
            field=models.BooleanField(default=True, help_text='Desligado: some da página de Encomenda (mas continua no cardápio).', verbose_name='aparece na encomenda'),
        ),
    ]
