# Generated by Django 5.0.14 on 2026-06-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0009_item_encomendavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='foto_mime',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
