# Generated by Django 5.0.14 on 2026-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0010_item_foto_item_foto_mime'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('foto_mime', models.CharField(blank=True, default='', max_length=60)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'foto do site',
                'verbose_name_plural': 'fotos do site',
            },
        ),
        migrations.CreateModel(
            name='TextoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=60, unique=True)),
                ('pt', models.TextField(blank=True)),
                ('en', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'texto do site',
                'verbose_name_plural': 'textos do site',
            },
        ),
    ]
